name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://joyotech.crm.dynamics.com/main.aspx?appid=a9f02600-045a-eb11-a812-002248047bc9&pagetype=entitylist&etn=almlab_timeoffrequest&viewid=48eca811-f7bc-4f26-b8f4-a786269bb9a4&viewType=1039'
        user-name: 'joyo'
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://joyotech.crm.dynamics.com/main.aspx?appid=a9f02600-045a-eb11-a812-002248047bc9&pagetype=entitylist&etn=almlab_timeoffrequest&viewid=48eca811-f7bc-4f26-b8f4-a786269bb9a4&viewType=1039'
        user-name: 'joyo'
        password-secret: ${{ secrets.password }}
        solution-name: ALMLab
        solution-output-file: out/exported/ALMLab.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/ALMLab.zip
        solution-folder: out/solutions/ALMLab
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/ALMLab
        solution-target-folder: solutions/ALMLab
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
